language: generic
env:
  global:
  - SWIFT_VERSION=5.2
matrix:
  include:
    - os: osx
      env: JOB=SwiftPM_OSX
      osx_image: xcode11
    - os: linux
      env: JOB=SwiftPM_linux
      dist: focal
      sudo: required
      install:
        -  travis_retry eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift build -c release
  - swift build
  - swift test --enable-test-discovery
